name: Reusable Workflow


on:
    workflow_call:

jobs:
    ru1-job1:
        runs-on: ubuntu-latest
        steps:
            - name: "Prueba de mensaje de reutlizacion"
              run: |
                echo "Estoy reutilizando un workflow ones"